[project]
name = "gerenciador-comandas"
version = "0.1.0"
description = ""
authors = [
    {name = "Felipe GuimarÃ£es",email = "89321902+guimaraesfe1@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "sqlalchemy (>=2.0.45,<3.0.0)",
    "fastapi[standard] (>=0.124.4,<0.125.0)",
    "alembic (>=1.17.2,<2.0.0)",
    "psycopg[binary] (>=3.3.2,<4.0.0)",
    "pydantic-settings (>=2.12.0,<3.0.0)"
]


[tool.poetry]
package-mode = false

[tool.pytest]
pythonpath = ['.']

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.2,<10.0.0)"
]
